### ISSUE TITLE
I want to add Chinese Characters to Matrix Rain!

### ISSUE THREAD

**Issue by liwuhou** [nojvek/matrix-rain#18]
I write some code. it looks awesome.

![2022-09-27 12-37-25 2022-09-27 12_39_17](https://user-images.githubusercontent.com/34914135/192433572-109347d2-059a-4a8d-a25c-75b43beec808.gif)

**Comment by nojvek** [comment]
Sure, make a PR. We have kanji support, chinese characters wouldn't be too hard.
