### ISSUE TITLE
Can't get font a non-gray color

### ISSUE THREAD

**Issue by wadewegner** [nojvek/matrix-rain#2]
Great utility. Unfortunately I can't get it to display with the Matrix-style green. Is there an opt for that?

**Comment by nojvek** [comment]
That's because when I programmed this, I didn't fully understand how ANSI works. I'll fix it

**Comment by ianizaguirre** [comment]
Has this been fixed, its still not green ?

**Comment by nojvek** [comment]
Will look into it. This totally fell off my plate. Sorry

**Comment by sabrehagen** [comment]
Any progress on this?

**Comment by nojvek** [comment]
Sorry, been super busy.

It's green if you're in a unix terminal, but I imagine you're in a windows terminal.

I will upgrade so it uses the chalk library.

**Comment by nojvek** [comment]
@ianizaguirre / @wadewegner / @sabrehagen - Apologies for the delay. I've pubished v2, it's a complete rewrite of matrix-rain with additional options such as emoji rain, braille rain and more colors.

Let me know what you think.

**Comment by nojvek** [comment]
Fixed by #3

**Comment by sabrehagen** [comment]
Colour is working, however it would be great to specify multiple character ranges e.g. [`-k braille,kanji`](https://github.com/nojvek/matrix-rain/blob/master/index.js#L91).

**Comment by nojvek** [comment]
We could open another issue for multiple character ranges if people really want it. I'm happy to accept PRs too. However realistically since its Vacation season, I may not get a chance to get on it.
