### ISSUE TITLE
kanji/katakana ranges

### ISSUE THREAD

**Issue by DyckGerman** [nojvek/matrix-rain#6]
https://github.com/nojvek/matrix-rain/blob/19869bab031f04d76a1a129c219323543af6775d/index.js#L101

btw, it is 'katakana' range (https://en.wikipedia.org/wiki/Katakana_(Unicode_block))

U+30F6 - U+30FF is a dangerous range. I am not sure but sometimes I see that symbols once I increase window size

**Comment by nojvek** [comment]
Thanks for the PR
